# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Specify the version of pre-commit
default_language_version:
  python: python3.8  # Adjust this to your Python version

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements  # Prevents `print` and `pdb` statements from being committed

  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use the latest stable version
    hooks:
      - id: black
        args: [--line-length=88]  # Match with .flake8 max-line-length

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0  # Use the latest stable version
    hooks:
      - id: flake8
        additional_dependencies: []
        args: [--config=.flake8]  # Ensure flake8 uses the configuration from .flake8 file

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0  # Use the latest stable version
    hooks:
      - id: isort
        args: ["--profile", "black"]  # Use isort with black-compatible settings

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  # Use the latest stable version
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-json

  - repo: https://github.com/pre-commit/mirrors-bandit
    rev: v1.7.0
    hooks:
      - id: bandit
        args: ["--skip=B101,B102"]  # Adjust the rules based on your project's security needs
